Animal.destroy_all

box = Animal.create(name: "Box Jellyfish", scientific_name: "Chironex fleckeri", location: "Northern Australia", danger_level: 10, description: "The venom immobilises your nerves and affects breathing and movement. A large dose can cause cardiac arrest and death within minutes", photo: "https://static01.nyt.com/images/2012/12/18/science/18OBFOSSIL/18OBFOSSIL-jumbo-v2.jpg")
taipan = Animal.create(name: "Taipan Snake", scientific_name: "Oxyuranus scutellatus", location: "Northwestern Australia", danger_level: 7, description: "The venom attacks the nervous system and blood. If bitten, you might start to bleed internally, as well as suffer headaches, nausea and vomiting", photo: "https://www.abc.net.au/news/image/10792958-3x2-700x467.jpg")
redback = Animal.create(name: "Redback Spider", scientific_name: "Latrodectus hasselti", location: "Australia", danger_level: 9, description: "The venom acts directly on the nerves, resulting in release and subsequent depletion of neurotransmitters.", photo: "https://media.australianmuseum.net.au/media/dd/images/Some_image.width-600.b5353e9.jpg")
saltwater = Animal.create(name: "Saltwater Crocodile", scientific_name: "Crocodylus porosus", location: "Ocean Australia", danger_level: 8, description: "Ambushes prey", photo: "https://images.immediate.co.uk/production/volatile/sites/23/2014/11/GettyImages-123529247-2a29d6c.jpg?quality=90&resize=620%2C413")
blueringed = Animal.create(name: "Blue-ringed Octopus", scientific_name: "Genus Hapalochlaena", location: "Ocean Australia", danger_level: 7, description: "Because it contains neurotoxins, the body starts to shut down and becomes increasingly paralysed. Usually victims die because they stop breathing", photo: "http://www.geek.com/wp-content/uploads/2018/12/blueringedoctopus.jpg")
stonefish = Animal.create(name: "Stonefish", scientific_name: "Synanceia verrucosa", location: "Northern Coast of Australia", danger_level: 10, description: "Dangerously venomous and can be fatal, the Steonfish is very hard to spot as it lies motionless and camouflaged", photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Stone_Fish_at_AQWA_SMC2006.jpg/220px-Stone_Fish_at_AQWA_SMC2006.jpg")
brown = Animal.create(name: "Brown Snake", scientific_name: "Pseudonaja textilis", location: "Eastern Australia", danger_level: 10, description: "The bite can be painless and difficult to detect. This is problematic because the venom can result in eventual paralysis and uncontrollable bleeding.", photo: "https://static.inaturalist.org/photos/9976454/original.jpg?1503573546")
greatwhite = Animal.create(name: "Great White Shark", scientific_name: "Carcharodon carcharias", location: "Ocean Australia", danger_level: 10, description: "Vicous bites are administered by rows of up to 300 sharp and serrated triangular teeth.", photo: "https://oceana.org/sites/default/files/styles/lightbox_full/public/noaa_white_shark_2.jpg?itok=aK_qqtXR")
funnel = Animal.create(name: "Sydney Funnel Web Spider", scientific_name: "Atrax robustus", location: "Sydney Australia", danger_level: 8, description: "The venom of a Sydney funnel web contains a neurotoxin component that affects the nervous system. The bite is very painful, and symptoms include sweating, tingling and muscle spasms.", photo: "https://cbsnews1.cbsistatic.com/hub/i/r/2016/03/08/992d678c-52b6-4c07-8c30-3db388d032d3/resize/620x465/b3c5d535cc399c5694fe13ed12ae3431/gettyimages-56714645.jpg")



