Animal.destroy_all


box = Animal.create(name: "Box Jellyfish", scientific_name: "Chironex fleckeri", location: "Northern Australia", danger_level: 10, description: "The venom immobilises your nerves and affects breathing and movement. A large dose can cause cardiac arrest and death within minutes", photo: "https://static01.nyt.com/images/2012/12/18/science/18OBFOSSIL/18OBFOSSIL-jumbo-v2.jpg")
taipan = Animal.create(name: "Taipan Snake", scientific_name: "Oxyuranus scutellatus", location: "Northwestern Australia", danger_level: 7, description: "The venom attacks the nervous system and blood. If bitten, you might start to bleed internally, as well as suffer headaches, nausea and vomiting", photo: "https://www.abc.net.au/news/image/10792958-3x2-700x467.jpg")
redback = Animal.create(name: "Redback Spider", scientific_name: "Latrodectus hasselti", location: "Australia", danger_level: 9, description: "The venom acts directly on the nerves, resulting in release and subsequent depletion of neurotransmitters.", photo: "https://media.australianmuseum.net.au/media/dd/images/Some_image.width-600.b5353e9.jpg")
saltwater = Animal.create(name: "Saltwater Crocodile", scientific_name: "Crocodylus porosus", location: "Ocean Australia", danger_level: 8, description: "Ambushes prey", photo: "https://images.immediate.co.uk/production/volatile/sites/23/2014/11/GettyImages-123529247-2a29d6c.jpg?quality=90&resize=620%2C413")
blueringed = Animal.create(name: "Blue-ringed Octopus", scientific_name: "Genus Hapalochlaena", location: "Ocean Australia", danger_level: 7, description: "Because it contains neurotoxins, the body starts to shut down and becomes increasingly paralysed. Usually victims die because they stop breathing", photo: "http://www.geek.com/wp-content/uploads/2018/12/blueringedoctopus.jpg")
stonefish = Animal.create(name: "Stonefish", scientific_name: "Synanceia verrucosa", location: "Northern Coast of Australia", danger_level: 10, description: "Dangerously venomous and can be fatal, the Steonfish is very hard to spot as it lies motionless and camouflaged", photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Stone_Fish_at_AQWA_SMC2006.jpg/220px-Stone_Fish_at_AQWA_SMC2006.jpg")
brown = Animal.create(name: "Brown Snake", scientific_name: "Pseudonaja textilis", location: "Eastern Australia", danger_level: 10, description: "The bite can be painless and difficult to detect. This is problematic because the venom can result in eventual paralysis and uncontrollable bleeding.", photo: "https://static.inaturalist.org/photos/9976454/original.jpg?1503573546")
greatwhite = Animal.create(name: "Great White Shark", scientific_name: "Carcharodon carcharias", location: "Ocean Australia", danger_level: 10, description: "Vicous bites are administered by rows of up to 300 sharp and serrated triangular teeth.", photo: "https://oceana.org/sites/default/files/styles/lightbox_full/public/noaa_white_shark_2.jpg?itok=aK_qqtXR")
funnel = Animal.create(name: "Sydney Funnel Web Spider", scientific_name: "Atrax robustus", location: "Sydney Australia", danger_level: 8, description: "The venom of a Sydney funnel web contains a neurotoxin component that affects the nervous system. The bite is very painful, and symptoms include sweating, tingling and muscle spasms.", photo: "https://cbsnews1.cbsistatic.com/hub/i/r/2016/03/08/992d678c-52b6-4c07-8c30-3db388d032d3/resize/620x465/b3c5d535cc399c5694fe13ed12ae3431/gettyimages-56714645.jpg")
honey = Animal.create(name: "Honey Bee", scientific_name: "Apis mellifera", location: "Sydney Australia", danger_level: 8, description: "kills via anaphylactic shock, usually obstructing airways", photo: "https://media.australianmuseum.net.au/media/dd/images/27d6ed29c62e9f8c1b69e924d94edce5.width-800.fd2a03c.jpg")
irukandji = Animal.create(name: "Irukandji Jellyfish", scientific_name: "Carukia barnesi", location: "Coastline Australia", danger_level: 7, description: "induces excruciating muscle cramps, severe pain in the back and kidneys, a burning sensation of the skin and face, headaches, nausea, restlessness, sweating, vomiting, and psychological phenomena such as the feeling of impending doom", photo: "https://cdn.newsapi.com.au/image/v1/b5946789400037cfe30df6d4f173b573?width=650")
bull = Animal.create(name: "Bull Shark", scientific_name: "Carcharhinus leucas", location: "Australian Waterways", danger_level: 8, description: "An aggressive shark that can inhabit both salt and freshwater. most dangerous in murky water", photo: "https://www.floridamuseum.ufl.edu/wp-content/uploads/sites/66/2018/08/DSnyder_Carcharhinus_leucas_GreatBahamaBank_Bahamas_DBS_4868-003-500x333.jpg")
tigerSnake = Animal.create(name: "Mainland Tiger Snake", scientific_name: "Notechis scutatus", location: "South Eastern Australia", danger_level: 10, description: "venom contains procoagulants and neurotoxins, causing paralysis and preventing blood clotting", photo: "https://www.australiazoo.com.au/our-animals/amazing-animals/images/black-tiger-snake.jpg")
mulga = Animal.create(name: "Mulga Snake", scientific_name: "Pseudechis australis", location: "Throughout Australia", danger_level: 6, description: "delivers high amounts of less potent myotoxins, resulting in severe muscular damage", photo: "https://media.australianmuseum.net.au/media/dd/images/Some_image.width-800.936829a.jpg")
copperHead = Animal.create(name: "Lowlands Copperhead", scientific_name: "Austrelaps superbus", location: "South Eastern Australia", danger_level: 5, description: "conatins postsynaptic neurotoxins, causing weaker but quicker muscle paralysis", photo: "https://lh3.googleusercontent.com/6fwcZGMvpXVg2266GpngElhFZ-MS_LxH7eaVPiIgSg8J_TZm_pQn83K3XiI--ZEaOdSZfOePKEo3pgVSoLAi=s580")
deathAdder = Animal.create(name: "Common Death Adder", scientific_name: "Acanthophis antarcticus", location: "Eastern and southern Australia", danger_level: 9, description: "Delivers one of the fastest bites of all snakes with a powerful neurotoxin that can kill within 6 hours", photo: "https://www.reptiletalk.net/wp-content/uploads/2016/11/Common-Death-Adder.jpg")
redBellied = Animal.create(name: "Red-Bellied black snake", scientific_name: "Pseudechis porphyriacus", location: "Eastern Coastal Australia", danger_level: 6, description: " Venom includes neurotoxins, myotoxins, and procoagulants, but antivenom is readilly availale and very effective", photo: "https://www.worldlifeexpectancy.com/images/a/w/b/pseudechis-porphyriacus/pseudechis-porphyriacus.jpg")

